ChallengeTopic/Models/ErrorViewModel.cs
using System;

namespace ChallengeTopic.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChallengeTopic/Controllers/HomeController.cs
using ChallengeTopic.ApplicationCore.Intefaces.Services;
using ChallengeTopic.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ChallengeTopic.Controllers
{
    public class HomeController : Controller
    {
        private readonly ITopicService topicService;
        public HomeController(ITopicService topicService)
        {
            this.topicService = topicService;
        }

        public IActionResult Index()
        {
            var topics = topicService.FindAll(0,100).ToList();
            return View(topics);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChallengeTopic/Controllers/TopicController.cs
using ChallengeTopic.ApplicationCore.Intefaces.Services;
using ChallengeTopic.ApplicationCore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChallengeTopic.Controllers
{
    public class TopicController : Controller
    {
        private readonly ITopicService topicService;
        public TopicController(ITopicService topicService)
        {
            this.topicService = topicService;
        }
        public IActionResult Index(int id)
        {
            var topic = topicService.GetByID(id);
            return View(topic);
        }
        public IActionResult New()
        {
            return View();
        }
        public IActionResult Edit(int id)
        {
            var topic = topicService.GetByID(id);
            return View(topic);
        }
        public IActionResult DeleteConfirmation(int id)
        {
            var topic = topicService.GetByID(id);
            return View(topic);
        }

        [HttpPost]
        public IActionResult New(Topic topic)
        {
            topic.CriationDate = DateTime.Now;
            topicService.Add(topic);
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult Edit(Topic topic)
        {
            topicService.Update(topic);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Delete(int id)
        {
            topicService.Delete(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

ChallengeTopic/Views/Home/Index.cshtml
@model List<ChallengeTopic.ApplicationCore.Models.Topic>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Here is the last ten topics.</p>

</div>

<div class="row text-left">

    <a class="btn btn-success" asp-area="" asp-controller="Topic" asp-action="New">Create new topic</a>
    @if (Model != null && Model.Any())
    {
        foreach (var topic in Model)
        {
            <div class="card objCard">
                <div class="card-body">
                    <h5 class="card-title">@topic.Title</h5>
                    <p class="card-text">
                        @topic.Content
                    </p>
                    <a class="btn btn-primary" asp-route-id="@topic.Id" asp-controller="Topic" asp-action="Index">View full topic</a>
                    <a class="btn btn-primary" asp-route-id="@topic.Id" asp-area="" asp-controller="Topic" asp-action="Edit">Edit</a>
                    <a class="btn btn-danger" asp-route-id="@topic.Id" asp-area="" asp-controller="Topic" asp-action="DeleteConfirmation">Delete</a>
                </div>
                <div class="card-footer">
                    <label>
                        Alexandre Campos Montalvão
                    </label> -
                    <label>
                        @topic.CriationDate
                    </label>
                </div>
            </div>

        }
    }
</div>

ChallengeTopic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChallengeTopic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChallengeTopic</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ChallengeTopic - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ChallengeTopic/Views/Topic/DeleteConfirmation.cshtml
@model ChallengeTopic.ApplicationCore.Models.Topic
@{
    ViewData["Title"] = "Delete topic";
}

<div class="text-center">
    <h3 class="display-4">Are you sure you want to delete this topic?</h3>
    <h3 class="display-4">@Model.Title</h3>
</div>
<div class="text-center">
    <a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="Index">No</a>
    <a class="btn btn-danger"  asp-route-id="@Model.Id" asp-controller="Topic" asp-action="Delete">Yes</a>
</div>

ChallengeTopic/Views/Topic/Edit.cshtml
@model ChallengeTopic.ApplicationCore.Models.Topic
@{
    ViewData["Title"] = "Edit Topic";
}

<div class="text-center">
    <h1 class="display-4">Topic</h1>
    <p>Here you can edit your topic.</p>

</div>
<form asp-controller="Topic" asp-action="Edit" method="post">
    <div class="text-left">
        <div class="row">
            <div class="mb-3 col-md-6">
                <label for="Title" class="form-label">Title</label>
                <input required class="form-control" asp-for="Title">
            </div>
            <div class="mb-3 col-md-12">
                <label for="Content" class="form-label">Content</label>
                <textarea required class="form-control" asp-for="Content" rows="6"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <button type="submit" class="btn btn-success">Save</button>
            </div>
            <div class="col-md-1">
                <a class="btn btn-danger" asp-area="" asp-controller="Home" asp-action="Index">Cancel</a>
            </div>
        </div>
    </div>
</form>

ChallengeTopic/Views/Topic/Index.cshtml
@model ChallengeTopic.ApplicationCore.Models.Topic
@{
    ViewData["Title"] = "Topic Page";
}

<div class="text-center">
    <h1 class="display-4">Topic</h1>
    <p>Here you can see the full topic.</p>

    <div class="card objCard">
        <div class="card-body">
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">
                @Model.Content
            </p>
            <a class="btn btn-primary" asp-route-id="@Model.Id" asp-controller="Topic" asp-action="Index">View full topic</a>
            <a class="btn btn-primary" asp-route-id="@Model.Id" asp-area="" asp-controller="Topic" asp-action="Edit">Edit</a>
            <a class="btn btn-danger" asp-route-id="@Model.Id" asp-area="" asp-controller="Topic" asp-action="DeleteConfirmation">Delete</a>
        </div>
        <div class="card-footer">
            <label>
                Alexandre Campos Montalvão
            </label> -
            <label>
                @Model.CriationDate
            </label>
        </div>
    </div>

    @*<a class="btn btn-primary" asp-area="" asp-controller="Topic" asp-action="Edit">Edit</a>
    <a class="btn btn-danger" asp-area="" asp-controller="Topic" asp-action="DeleteConfirmation">Delete</a>*@
</div>

ChallengeTopic/Views/Topic/New.cshtml
@model ChallengeTopic.ApplicationCore.Models.Topic
@{
    ViewData["Title"] = "New Topic";
}

<div class="text-center">
    <h1 class="display-4">Topic</h1>
    <p>Here you can create your topic.</p>

</div>
<form asp-controller="Topic" asp-action="New" method="post">
    <div class="text-left">
        <div class="row">
            <div class="mb-3 col-md-6">
                <label for="Title" class="form-label">Title</label>
                <input required class="form-control" asp-for="Title">
            </div>
            <div class="mb-3 col-md-12">
                <label for="Content" class="form-label">Content</label>
                <textarea required class="form-control" asp-for="Content" rows="6"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
                <button type="submit" class="btn btn-success">Save</button>
            </div>
            <div class="col-md-1">
                <a class="btn btn-danger" asp-area="" asp-controller="Home" asp-action="Index">Cancel</a>
            </div>
        </div>
    </div>
</form>